FROM python:2.7-onbuild

# Install blast, cron and rsync
RUN apt-get update
RUN apt-get install -y ncbi-blast\+ rsync cron

RUN chmod 0755 /usr/src/app/schedule_updates.bash /usr/src/app/update_databanks.bash

CMD ["/bin/bash", "/usr/src/app/schedule_updates.bash"]
