FROM python:3.5

# hommod
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r requirements.txt
COPY . /usr/src/app

RUN apt-get update && apt-get install -y clustalw

EXPOSE 7001
