from nose.tools import with_setup, eq_
from hommod_rest.services.model import modeler
import hommod_rest.default_settings as config


def setup():
    modeler.yasara_dir = config.YASARADIR
    modeler.execution_root_dir = config.EXECUTIONDIR
    modeler.model_root_dir = config.MODELDIR
    modeler.template_blacklist = config.TEMPLATE_BLACKLIST


def teardown():
    pass


@with_setup(setup, teardown)
def test_set_template():
    obj, oligomerization = modeler._set_template("3DS1")

    assert obj is not None
    assert oligomerization >= 1

@with_setup(setup, teardown)
def test_set_4RH7_A():
    obj, oligomerization = modeler._set_template("4RH7")

    seq_expected = ("QGEVTIREALRELDLWGVGAVFTLIDYEDSQSRTMKLIKDWKDIVNQVGDNRCL" +
                    "LQSLKDSPYYKGFEDKVSIWERKLAELDEYLQNLNHIQRKWVYLEPIFGRGALP" +
                    "KEQTRFNRVDEDFRSIMTDIKKDNRVTTLTTHAGIRNSLLTILDQLQRCQRSLN" +
                    "EFLEEKRSAFPRFYFIGDDDLLEILGQSTNPSVIQSHLKKLFAGINSVCFDEKS" +
                    "KHITAMKSLEGEVVPFKNKVPLSNNVETWLNDLALEMKKTLEQLLKECVTTGRS" +
                    "SQGAVDPSLFPSQILCLAEQIKFTEDVENAIKDHSLHQIETQLVNKLEQYTNID" +
                    "TSSEDPGNTESGILELKLKALILDIIHNIDVVKQLNQIQVHTTEDWAWKKQLRF" +
                    "YMKSDHTCCVQMVDSEFQYTYEYQGNASKLVYTPLTDKCYLTLTQAMKMGLGGN" +
                    "PYGPAGTGKTESVKALGGLLGRQVLVFNCDEGIDVKSMGRIFVGLVKCGAWGCF" +
                    "DEFNRLEESVLSAVSMQIQTIQDALKNHRTVCELLGKEVEVNSNSGIFITMNPA" +
                    "GKGYGGRQKLPDNLKQLFRPVAMSHPDNELIAEVILYSEGFKDAKVLSRKLVAI" +
                    "FNLSRELLTPQQHYDWGLRALKTVLRGSGNLLRQLNKSGTTQNANESHIVVQAL" +
                    "RLNTMSKFTFTDCTRFDALIKDVFPGIELKEVEYDELSAALKQVFEEANYEIIP" +
                    "NQIKKALELYEQLCQRMGVVIVGPSGAGKSTLWRMLRAALCKTGKVVKQYTMNP" +
                    "KAMPRYQLLGHIDMDTREWSDGVLTNSARQVVREPQDVSSWIICDGDIDPEWIE" +
                    "SLNSVLDDNRLLTMPSGERIQFGPNVNFVFETHDLSCASPATISRMGMIFLSDE" +
                    "ETDLNSLIKSWLRNQPAEYRNNLENWIGDYFEKALQWVLKQNDYVVETSLVGTV" +
                    "MNGLSHLHGCRDHDEFIINLIRGLGGNLNMKSRLEFTKEVFHWARESPPDFHKP" +
                    "MDTYYDSTRGRLATYVLKKPEDLTADDFSNGLTLPVIQTPDMQRGLDYFKPWLS" +
                    "SDTKQPFILVGPEGCGKGMLLRYAFSQLRSTQIATVHCSAQTTSRHLLQKLSQT" +
                    "CMVISTNTGRVYRPKDCERLVLYLKDINLPKLDKWGTSTLVAFLQQVLTYQGFY" +
                    "DENLEWVGLENIQIVASMSAGGRLGRHKLTTRFTSIVRLCSIDYPEREQLQTIY" +
                    "GAYLEPVLHKNLKNHSIWGSSSKIYLLAGSMVQVYEQVRAKFTVDDYSHYFFTP" +
                    "CILTQWVLGLFRYDLEGGSSNHPLDYVLEIVAYEARRLFRDKIVGAKELHLFDI" +
                    "ILTSVFQGDWGSDILDNMSDSFYVTWGARHNSGAPGQPLPPHGKPLGKLNSTDL" +
                    "KDVIKKGLIHYGRDNQNLDILLFHEVLEYMSRIDRVLSFPGGSLLLAGRSGVGR" +
                    "RTITSLVSHMHGAVLFSPKISRGYELKQFKNDLKHVLQLAGIEAQQVVLLLEDY" +
                    "QFVHPTFLEMINSLLSSGEVPGLYTLEELEPLLLPLKDQASQDGFFGPVFNYFT" +
                    "YRIQQNLHIVLIMDSANSNFMINCESNPALHKKCQVLWMEGWSNSSMKKIPEML" +
                    "FSEVDPDFLKSFLLIHESCKAYGATPSQYMTFLHVYSAISSSKKKELLKRQSHL" +
                    "QAGVSKLNEAKALVDELNRKAGEQSVLLKTKQDEADAALQMITVSMQDASEQKT" +
                    "ELERLKHRIAEEVVKIEERKNKIDDELKEVQPLVNEAKLAVGNIKPESLSEIRS" +
                    "LRMPPDVIRDILEGVLRLMGIFDTSWVSMKSFLAKRGVREDIATFDARNISKEI" +
                    "RESVEELLFKNKGSFDPKNAKRASTAAAPLAAWVKANIQYSHVLERIHPLETEQ" +
                    "AGLESNLKKTEDRKRKLEELLNSVGQKVSELKEKFQSRTSEAAKLEAEVSKAQE" +
                    "TIKAAEVLINQLDREHKRWNAQVVEITEELATLPKRAQLAAAFITYLSAAPESL" +
                    "RKTCLEEWTKSAGLEKFDLRRFLCTESEQLIWKSEGLPSDDLSIENALVILQSR" +
                    "VCPFLIDPSSQATEWLKTHLKDSRLEVINQQDSNFITALELAVRFGKTLIIQEM" +
                    "DGVEPVLYPLLRRDLVAQGPRYVVQIGDKIIDYNEEFRLFLSTRNPNPFIPPDA" +
                    "ASIVTEVNFTTTRSGLRGQLLALTIQHEKPDLEEQKTKLLQQEEDKKIQLAKLE" +
                    "ESLLETLATSQGNILENKDLIESLNQTKASSALIQESLKESYKLQISLDQERDA" +
                    "YLPLAESASKMYFIISDLSKINNMYRFSLAAFLRLFQRALQNKQDSENTEQRIQ" +
                    "SLISSLQHMVYEYICRCLFKADQLMFALHFVRGMHPELFQENEWDTFTGVDQLP" +
                    "SWIDQERSWAVATLKIALPSLYQTLCFEDAALWRTYYNNSMCEQEFPSILAKKV" +
                    "SLFQQILVVQVLRPDRLQSAMALFACKTLGLKEVSPLPLNLKRLYKETLEIEPI" +
                    "LIIISPGADPSQELQELANAERSGECYHQVAMGQGQADLAIQMLKECARNGDWL" +
                    "CLKNLHLVVSWLPVLEKELNTLQPKDTFRLWLTAEVHPNFTPILLQSSLKITYE" +
                    "SPPGLKKNLMRTYESWTPEQISKKDNTHRAHALFSLAWFHAACQERRNYIPQGW" +
                    "TKFYEFSLSDLRAGYNIIDRLFDGAKDVQWEFVHGLLENAIYGGRIDNYFDLRV" +
                    "LQSYLKQFFNSSVIIFPYSVSLPQSCSILDYRAVIEKIPEDDKPSFFGLPANIA" +
                    "RSSQRMISSQVISQLRILGRSITAGSKFDREIWSNELSPVLNLWKKLNQNSNLI" +
                    "HQKVPPPNDRQGSPILSFIILEQFNAIRLVQSVHQSLAALSKVIRGTTLLSSEV" +
                    "QKLASALLNQKCPLAWQSKWEGPEDPLQYLRGLVARALAIQNWVDKAEKQALLS" +
                    "ETLDLSELFHPDTFLNALRQETARAVGRSVDSLKFVASWKGRLQEAKLQIKISG" +
                    "LLLEGCSFDGNQLSENQLDSPSVSSVLPCFMGWIPQDACGPYSPDECISLPVYT" +
                    "SAERDRVVTNIDVPCGGNQDQWIQCGAALFLKNQV")
    seq_actual = modeler.yasara.SequenceMol("obj %i mol %s" % (obj, 'A'))[0]
    eq_(seq_expected, seq_actual)

def test_set_5MQF_A():
    obj, oligomerization = modeler._set_template("5MQF")

    seq_expected = ("SEEKLQEKARKWQQLQAKRYAEKRKFGFVD" +
                    "AQKEDMPPEHVRKIIRDHGDMTNRKFRHDKRVYLGALKYMPHAVLKLLENMPMPW" +
                    "EQIRDVPVLYHITGAISFVNEIPWVIEPVYISQWGSMWIMMRREKRDRRHFKRMR" +
                    "FPPFDDEEPPLDYADNILDVEPLEAIQLELDPEEDAPVLDWFYDHQPLRDSRKYV" +
                    "NGSTYQRWQFTLPMMSTLYRLANQLLTDLVDDNYFYLFDLKAFFTSKALNMAIPG" +
                    "GPKFEPLVRDINLQDEDWNEFNDINKIIIRQPIRTEYKIAFPYLYNNLPHHVHLT" +
                    "WYHTPNVVFIKTEDPDLPAFYFDPLINPISHRHSVKSQEPLPDDDEEFELPEFVE" +
                    "PFLKDTPLYTDNTANGIALLWAPRPFNLRSGRTRRALDIPLVKNWYREHCPAGQP" +
                    "VKVRVSYQKLLKYYVLNALKHRPPKAQKKRYLFRSFKATKFFQSTKLDWVEVGLQ" +
                    "VCRQGYNMLNLLIHRKNLNYLHLDYNFNLKPVKTLTTKERKKSRFGNAFHLCREV" +
                    "LRLTKLVVDSHVQYRLGNVDAFQLADGLQYIFAHVGQLTGMYRYKYKLMRQIRMC" +
                    "KDLKHLIYYRFNTGPVGKGPGCGFWAAGWRVWLFFMRGITPLLERWLGNLLARQF" +
                    "EGRHSKGVAKTVTKQRVESHFDLELRAAVMHDILDMMPEGIKQNKARTILQHLSE" +
                    "AWRCWKANIPWKVPGLPTPIENMILRYVKAKADWWTNTAHYNRERIRRGATVDKT" +
                    "VCKKNLGRLTRLYLKAEQERQHNYLKDGPYITAEEAVAVYTTTVHWLESRRFSPI" +
                    "PFPPLSYKHDTKLLILALERLKEAYSVKSRLNQSQREELGLIEQAYDNPHEALSR" +
                    "IKRHLLTQRAFKEVGIEFMDLYSHLVPVYDVEPLEKITDAYLDQYLWYEADKRRL" +
                    "FPPWIKPADTEPPPLLVYKWCQGINNLQDVWETSEGECNVMLESRFEKMYEKIDL" +
                    "TLLNRLLRLIVDHNIADYMTAKNNVVINYKDMNHTNSYGIIRGLQFASFIVQYYG" +
                    "LVMDLLVLGLHRASEMAGPPQMPNDFLSFQDIATEAAHPIRLFCRYIDRIHIFFR" +
                    "FTADEARDLIQRYLTEHPDPNNENIVGYNNKKCWPRDARMRLMKHDVNLGRAVFW" +
                    "DIKNRLPRSVTTVQWENSFVSVYSKDNPNLLFNMCGFECRILPKCRTSYEEFTHK" +
                    "DGVWNLQNEVTKERTAQCFLRVDDESMQRFHNRVRQILMASGSTTFTKIVNKWNT" +
                    "ALIGLMTYFREAVVNTQELLDLLVKCENKIQTRIKIGLNSKMPSRFPPVVFYTPK" +
                    "ELGGLGMLSMGHVLIPQSDLRWSKQTDVGITHFRSGMSHEEDQLIPNLYRYIQPW" +
                    "ESEFIDSQRVWAEYALKRQEAIAQNRRLTLEDLEDSWDRGIPRINTLFQKDRHTL" +
                    "AYDKGWRVRTDFKQYQVLKQNPFWWTHQRHDGKLWNLNNYRTDMIQALGGVEGIL" +
                    "EHTLFKGTYFPTWEGLFWEKASGFEESMKWKKLTNAQRSGLNQIPNRRFTLWWSP" +
                    "TINRANVYVGFQVQLDLTGIFMHGKIPTLKISLIQIFRAHLWQKIHESIVMDLCQ" +
                    "VFDQELDALEIETVQKETIHPRKSYKMNSSCADILLFASYKWNVSRPSLLADSKD" +
                    "VMDSTTTQKYWIDIQLRWGDYDSHDIERYARAKFLDYTTDNMSIYPSPTGVLIAI" +
                    "DLAYNLHSAYGNWFPGSKPLIQQAMAKIMKANPALYVLRERIRKGLQLYSSEPTE" +
                    "PYLSSQNYGELFSNQIIWFVDDTNVYRVTIHKTFEGNLTTKPINGAIFIFNPRTG" +
                    "QLFLKIIHTSVWAGQKRLGQLAKWKTAEEVAALIRSLPVEEQPKQIIVTRKGMLD" +
                    "PLEVHLLDFPNIVIKGSELQLPFQACLKVEKFGDLILKATEPQMVLFNLYDDWLK" +
                    "TISSYTAFSRLILILRALHVNNDRAKVILKPDKTTITEPHHIWPTLTDEEWIKVE" +
                    "VQLKDLILAD")
    seq_actual = modeler.yasara.SequenceMol("obj %i mol %s" % (obj, 'A'))[0]
    eq_(seq_expected, seq_actual)
