from hommod_rest.factory import create_app, create_celery_app

class TestTasks(object):

    @classmethod
    def setupClass(self):

        self.app = create_app({'TESTING': True, \
                               'CELERY_ALWAYS_EAGER': True,
                               'YASARADIR': '/home/cbaakman/Yasara/yasara'})
        self.celery = create_celery_app(self.app)

    def test_submit(self):

        r=self.app.test_client().post('/submit/',data={'position': 100, 'sequence': \
"MGAARGSPARPRRLPLLSVLLLPLLGGTQTAIVFIKQPSSQDALQGRRALLRCEVEAPGPVHVYWLLDGAPVQD" + \
"TERRFAQGSSLSFAAVDRLQDSGTFQCVARDDVTGEEARSANASFNIKWIEAGPVVLKHPASEAEIQPQTQVTL" + \
"RCHIDGHPRPTYQWFRDGTPLSDGQSNHTVSSKERNLTLRPAGPEHSGLYSCCAHSAFGQACSSQNFTLSIADE" + \
"SFARVVLAPQDVVVARYEEAMFHCQFSAQPPPSLQWLFEDETPITNRSRPPHLRRATVFANGSLLLTQVRPRNA" + \
"GIYRCIGQGQRGPPIILEATLHLAEIEDMPLFEPRVFTAGSEERVTCLPPKGLPEPSVWWEHAGVRLPTHGRVY" + \
"QKGHELVLANIAESDAGVYTCHAANLAGQRRQDVNITVATVPSWLKKPQDSQLEEGKPGYLDCLTQATPKPTVV" + \
"WYRNQMLISEDSRFEVFKNGTLRINSVEVYDGTWYRCMSSTPAGSIEAQARVQVLEKLKFTPPPQPQQCMEFDK" + \
"EATVPCSATGREKPTIKWERADGSSLPEWVTDNAGTLHFARVTRDDAGNYTCIASNGPQGQIRAHVQLTVAVFI" + \
"TFKVEPERTTVYQGHTALLQCEAQGDPKPLIQWKDKPVPEESEGPGSPPPYKMIQTIGLSVGAAVAYIIAVLGL" + \
"MFYCKKRCKAKRLQKQPEGEEPEMECLNGGPLQNGQPSAEIQEEVALTSLGSGPAATNKRHSTSDKMHFPRSSL" + \
"QPITTLGKSEFGEVFLAKAQGLEEGVAETLVLVKSLQSKDEQQQLDFRRELEMFGKLNHANVVRLLGLCREAEP" + \
"HYMVLEYVDLGDLKQFLRISKSKDEKLKSQPLSTKQKVALCTQVALGMEHLSNNRFVHKDLAARNCLVSAQRQV" + \
"KVSALGLSKDVYNSEYYHFRQAWVPLRWMSPEAILEGDFSTKSDVWAFGVLMWEVFTHGEMPHGGQADDEVLAD" + \
"LQAGKARLPQPEGCPSKLYRLMQRCWALSPKDRPSFSEIASALGDSTVDSKP" })

